# -*- coding: utf-8 -*-
"""Kaspa Backend.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19VFCvTlbWL6XhorIEk6mFJRMLz9VHl1E
"""

from flask import Flask, jsonify
import requests
import pandas as pd
from apscheduler.schedulers.background import BackgroundScheduler

app = Flask(__name__)

# Global variable to store the latest data
latest_data = {}

def fetch_data():
    global latest_data
    url = "https://api.coingecko.com/api/v3/coins/kaspa/market_chart"
    params = {
        'vs_currency': 'usd',
        'days': '365',
        'interval': 'daily'
    }
    response = requests.get(url, params=params)
    data = response.json()

    # Process data
    prices = data['prices']
    volumes = data['total_volumes']
    market_caps = data['market_caps']

    df = pd.DataFrame(prices, columns=['timestamp', 'price'])
    df['volume'] = [v[1] for v in volumes]
    df['market_cap'] = [m[1] for m in market_caps]
    df['date'] = pd.to_datetime(df['timestamp'], unit='ms')
    df = df.drop(columns=['timestamp'])

    # Calculate risk metrics
    df['daily_return'] = df['price'].pct_change()
    volatility = df['daily_return'].std()
    df['cumulative_return'] = (1 + df['daily_return']).cumprod()
    df['drawdown'] = df['cumulative_return'] / df['cumulative_return'].cummax() - 1
    max_drawdown = df['drawdown'].min()

    # Store the latest data
    latest_data = {
        'volatility': volatility,
        'max_drawdown': max_drawdown,
        'latest_price': df['price'].iloc[-1],
        'latest_volume': df['volume'].iloc[-1],
        'latest_market_cap': df['market_cap'].iloc[-1]
    }

# Schedule data fetching every hour
scheduler = BackgroundScheduler()
scheduler.add_job(fetch_data, 'interval', hours=1)
scheduler.start()

# API endpoint to get the latest data
@app.route('/data', methods=['GET'])
def get_data():
    return jsonify(latest_data)

if __name__ == '__main__':
    fetch_data()  # Fetch data immediately on startup
    app.run(debug=True)


import requests
response = requests.get('http://127.0.0.1:5000/data')
print(response.json())
